CREATE SCHEMA IF NOT EXISTS PAYMENT_SYSTEM;

SET SCHEMA PAYMENT_SYSTEM;

/************************************************/
/* ACCOUNT  */
/************************************************/

CREATE TABLE PAYMENT_SYSTEM.ACCOUNT (
  ID NUMERIC NOT NULL,
  NAME VARCHAR(10) NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL
);

ALTER TABLE PAYMENT_SYSTEM.ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID);

CREATE SEQUENCE PAYMENT_SYSTEM.ACCOUNT_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

INSERT INTO PAYMENT_SYSTEM.ACCOUNT (ID, NAME, AMOUNT) VALUES (PAYMENT_SYSTEM.ACCOUNT_ID_SEQ.nextval,'User-1', 100.00);
INSERT INTO PAYMENT_SYSTEM.ACCOUNT (ID, NAME, AMOUNT) VALUES (PAYMENT_SYSTEM.ACCOUNT_ID_SEQ.nextval,'User-2', 500.00);


/************************************************/
/* TRANSACTION  */
/************************************************/

CREATE TABLE PAYMENT_SYSTEM.TRANSACTION (
  ID              NUMBER        NOT NULL,
  FROM_ACCOUNT_ID         NUMBER        NOT NULL,
  TO_ACCOUNT_ID         NUMBER        NOT NULL,
  AMOUNT          DECIMAL(10,2) NOT NULL,
  OLD_BALANCE_FROM_ACCOUNT DECIMAL(10,2) NOT NULL,
  NEW_BALANCE_FROM_ACCOUNT DECIMAL(10,2) NOT NULL,
  OLD_BALANCE_TO_ACCOUNT DECIMAL(10,2) NOT NULL,
  NEW_BALANCE_TO_ACCOUNT DECIMAL(10,2) NOT NULL,
  DONE_ON DATE NOT NULL,
);

ALTER TABLE PAYMENT_SYSTEM.TRANSACTION ADD CONSTRAINT TRANSACTION_PK PRIMARY KEY (ID);

ALTER TABLE PAYMENT_SYSTEM.TRANSACTION ADD CONSTRAINT TRANSACTION_FK1 FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES PAYMENT_SYSTEM.ACCOUNT(ID);
ALTER TABLE PAYMENT_SYSTEM.TRANSACTION ADD CONSTRAINT TRANSACTION_FK2 FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES PAYMENT_SYSTEM.ACCOUNT(ID);

CREATE SEQUENCE PAYMENT_SYSTEM.TRANSACTION_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;





